eureka:
  instance:
    hostname: j12d204.p.ssafy.io  # ✅ EC2 도메인 기준으로 Eureka가 자신을 인식
  client:
    service-url:
      defaultZone: http://j12d204.p.ssafy.io:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway, readiness, liveness
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
