spring:
  profiles:
    active: dev
  application:
    name: locket-api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "Authorization, Content-Disposition"
            maxAge: 3600
      routes:
        # 서비스 라우팅
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          order: 100

        - id: elasticsearch-service
          uri: lb://ELASTICSEARCH-SERVICE
          predicates:
            - Path=/api/elasticsearch/**

        # Swagger 관련 경로
#        - id: openapi
#          uri: lb://LOCKET-API-GATEWAY
#          predicates:
#            - Path=/v3/api-docs/**, /swagger-ui/**, /webjars/**
#          filters:
#            - RewritePath=/(?<segment>.*), /$\{segment}


        # 서비스별 API 문서 경로
        - id: payment-service-docs
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/v3/api-docs

        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/v3/api-docs
          filters:
            - RewritePath=/api/users/v3/api-docs, /user-docs
          order: 1

        - id: elasticsearch-service-docs
          uri: lb://ELASTICSEARCH-SERVICE
          predicates:
            - Path=/api/elasticsearch/v3/api-docs
          filters:
            - RewritePath=/api/elasticsearch/v3/api-docs, /elasticsearch/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, gateway
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: ${JWT_SECRET:my-secret-jwt-key-for-dev-only}
  access-exp: ${JWT_ACCESS_EXP:86400000}
  refresh-exp: ${JWT_REFRESH_EXP:604800000}

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
#      - name: "API Gateway"
#        url: /v3/api-docs
      - name: "Locket Payment Service"
        url: http://localhost:8080/api/payment/v3/api-docs
      - name: "Locket User Service"
        url: http://localhost:8080/api/users/v3/api-docs
      - name: "Locket ElasticSearch Service"
        url: /api/elasticsearch/v3/api-docs