server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "Authorization, Content-Disposition"

      routes:
        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api/payment/(?<path>.*), /$\{path}

        - id: elasticsearch-service
          uri: http://elasticsearch-service:8083
          predicates:
            - Path=/api/elasticsearch/**
          filters:
            - RewritePath=/api/elasticsearch/(?<path>.*), /$\{path}

        # Swagger UI 경로 지원 (선택)
        - id: swagger-elasticsearch-docs
          uri: http://elasticsearch-service:8083
          predicates:
            - Path=/elasticsearch-docs/**

        - id: swagger-payment-docs
          uri: http://payment-service:8082
          predicates:
            - Path=/payment-docs/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j12d204.p.ssafy.io:8761/eureka
  instance:
    hostname: gateway-service
    instance-id: gateway-service:${server.port}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway, readiness, liveness
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

# Swagger URL 확인용 서버 URL 설정 (Optional)
swagger:
  server-url: https://j12d204.p.ssafy.io
