spring:
  config:
    activate:
      on-profile: prod

eureka:
  instance:
    instance-id: ${HOSTNAME}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j12d204.p.ssafy.io:8761/eureka

server:
  port: 8080

# ✅ 원격 서버에서 실행할 API 문서 경로
springdoc:
  swagger-ui:
    urls:
      - name: "Locket Payment Service"
        url: /api/payment/v3/api-docs
      - name: "Locket User Service"
        url: /api/users/v3/api-docs
      - name: "Locket ElasticSearch Service"  # ✅ Elasticsearch 추가
        url: /api/elasticsearch/v3/api-docs
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, gateway, readiness, liveness, info
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
