spring:
  config:
    activate:
      on-profile: prod

  application:
    name: locket-api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "Authorization, Content-Disposition"
      routes:
        # 서비스 라우팅
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api/payment/(?<segment>/?.*), /${segment}
          order: 10

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
          order: 10

        - id: elasticsearch-service
          uri: lb://ELASTICSEARCH-SERVICE
          predicates:
            - Path=/api/elasticsearch/**
          filters:
            - RewritePath=/api/elasticsearch/(?<segment>/?.*), /${segment}
            - RemoveRequestHeader=Host
          order: 10

        - id: locket-ai-service
          uri: lb://LOCKET-AI-SERVICE
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=2

        # 서비스별 Swagger 문서 라우팅
        - id: payment-service-docs
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/v3/api-docs/**
          filters:
            - RewritePath=/api/payment/v3/api-docs(?<remaining>/?.*), /payment-docs${remaining}
          order: 1

        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/v3/api-docs/**
          filters:
            - RewritePath=/api/users/v3/api-docs(?<remaining>/?.*), /users-docs${remaining}
          order: 1

#        - id: elasticsearch-service-docs
#          uri: lb://ELASTICSEARCH-SERVICE
#          predicates:
#            - Path=/api/elasticsearch/v3/api-docs/**
#          filters:
#            - RewritePath=/api/elasticsearch/v3/api-docs(?<remaining>/?.*), /elasticsearch-docs${remaining}
#            - RemoveRequestHeader=Host
#          order: 1

        - id: elasticsearch-service-docs
          uri: lb://ELASTICSEARCH-SERVICE
          predicates:
            - Path=/api/elasticsearch/v3/api-docs/**
          filters:
            - RewritePath=/api/elasticsearch/v3/api-docs(?<remaining>/?.*), /v3/api-docs${remaining}
            - RemoveRequestHeader=Host
          order: 1




eureka:
  instance:
    instance-id: api-gateway:${server.port}
    prefer-ip-address: false
    hostname: api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j12d204.p.ssafy.io:8761/eureka

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: "1. Locket User Service"
        url: https://j12d204.p.ssafy.io/api/users/v3/api-docs
      - name: "2. Locket Payment Service"
        url: https://j12d204.p.ssafy.io/api/payment/v3/api-docs
      - name: "3. Locket ElasticSearch Service"
        url: https://j12d204.p.ssafy.io/api/elasticsearch/v3/api-docs
#        url: https://j12d204.p.ssafy.io:8083/elasticsearch-docs

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, gateway, readiness, liveness, info
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
