version: '3.8'

services:
  discovery:
    image: maru1203/spring-locket-discovery:latest
    ports:
      - "8761:8761"
    networks:
      - spring-locket
      - monitoring

  user-service:
    image: maru1203/spring-locket-user-service:latest
    ports:
      - "8082:8082"
    networks:
      - spring-locket
      - monitoring
    depends_on:
      - discovery

  payment-service:
    image: maru1203/spring-locket-payment-service:latest
    ports:
      - "8081:8081"
    networks:
      - spring-locket
      - monitoring

  api-gateway:
    image: maru1203/spring-locket-api-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - spring-locket
      - monitoring

networks:
  spring-locket:
    external: true
  monitoring:
    external: true
