server:
  port: 0  # 랜덤 포트 사용

spring:
  application:
    name: payment-service

  profiles:
    include: key  # application-key.yml 포함 (DB, Kafka 정보)

  datasource:
    url: ${DB.URL_PAYMENT}  # key 파일에서 가져옴
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 필요에 따라 변경 가능

  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP-SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: manual

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

springdoc:
  api-docs:
    enabled: true
    path: /api/payment/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
