server:
  port: 8081  # 랜덤 포트 사용

spring:
  application:
    name: payment-service
  profiles:
    active: dev
    include: key  # application-key.yml 포함 (DB, Kafka 정보)

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 필요에 따라 변경 가능

  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP-SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: manual

  data:
    redis:
      host: j12d204.p.ssafy.io
      port: 6379
      password: ${REDIS.PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

springdoc:
  api-docs:
    enabled: true
    path: /api/payment/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET:my-secret-jwt-key-for-dev-only}
  access-exp: ${JWT_ACCESS_EXP:86400000}   # 24시간
  refresh-exp: ${JWT_REFRESH_EXP:604800000} # 7일
