spring:
  config:
    activate:
      on-profile: dev

  profiles:
    include: key  # application-key.yml 포함 (DB, Kafka 정보)

  elasticsearch:
    uris: ${ELASTICSEARCH.URIS}
    username: ${ELASTICSEARCH.USERNAME}
    password: ${ELASTICSEARCH.PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
