spring:
  config:
    activate:
      on-profile: prod

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://j12d204.p.ssafy.io:8761/eureka

