server:
  tomcat:
    relaxed-host-chars: "_"
  port: 8082  # 랜덤 포트 사용

spring:
  application:
    name: user-service
  profiles:
    active: dev
    include: key  # application-key.yml 포함 (DB, Kafka 정보) 

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 필요에 따라 변경 가능

  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP-SERVERS}
    consumer:
      group-id: ${KAFKA.CONSUMER.USER-GROUP-ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual_immediate

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

  data:
    redis:
      host: j12d204.p.ssafy.io
      port: 6379
      password: ${REDIS.PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, gateway
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /users-docs
  swagger-ui:
    path: /users-docs/swagger-ui.html
    display-request-duration: true
    filter: true
    use-root-path: true
  model-converters:
    pageable-converter:
      enabled: true
  models:
    schema-format: JSON_SCHEMA
    show-actuator: false
    override-with-generic-response: false
    use-fqn: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSecretKeyThatHasMoreThan256BitsToMeetTheSecurityRequirementsOfHMACSHA256AlgorithmUsedByJWTLibrary12345678901234567890}
  access-exp: ${JWT_ACCESS_EXP:86400000}   # 24시간
  refresh-exp: ${JWT_REFRESH_EXP:604800000} # 7일


receipt:
  service:
    url: http://localhost:8000 # Receipt 서비스 URL