server:
  port: 0  # 랜덤 포트 사용

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

springdoc:
  api-docs:
    enabled: true
    path: /api/user/v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json