server:
  port: 8082

spring:
  application:
    name: locket-user-service

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://locket-discovery:8761/eureka/

logging:
  level:
    org.apache.kafka: INFO
