spring:
  datasource:
    url: ${DB.URL_USER}  # user-service용 DB URL
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 자동 업데이트 허용
    show-sql: true  # SQL 쿼리 로그 출력 (디버깅용)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka  # 로컬 Eureka 서버 사용

swagger:
  server-url: http://localhost:8080/api/users