server:
  port: 8082

spring:
  config:
    activate:
      on-profile: prod

  kafka:
    consumer:
      group-id: user-service-group-prod

  datasource:
    url: ${DB_URL_USER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # 배포 환경에서는 스키마 자동 변경 방지
    show-sql: false  # SQL 로그 비활성화 (성능 최적화)

  data:
    redis:
      host: j12d204.p.ssafy.io
      port: 6379
      password: ${REDIS_PASSWORD}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j12d204.p.ssafy.io:8761/eureka  # EC2의 Eureka 서버 사용

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway, readiness, liveness
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
