plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.locket.payment'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
    set('springCloudVersion', "2023.0.3")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client' // Eureka Client

	// Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Actuator & Monitoring
    implementation 'org.springframework.boot:spring-boot-starter-actuator' // Spring Actuator
    implementation 'io.micrometer:micrometer-registry-prometheus' // Prometheus 연동
    
    // Feign Client
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // OpenAPI (Swagger)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

    // JWT (Optional, 필요 시 사용)
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // Spring Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // JPA + H2 (임시 DB) or MySQL (실제 운영 DB)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2' // 로컬 개발용 (운영은 MySQL 사용)
    runtimeOnly 'mysql:mysql-connector-java' // MySQL 사용 시

    // Spring Boot Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Resilience4j (Circuit Breaker)
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
